FROM alpine

WORKDIR '/app'

RUN apk add --update nodejs npm

RUN apk add --no-cache git

COPY package.json .


RUN npm install


RUN apk update

RUN apk add --update py3-pip
RUN pip3 install awsebcli

COPY . .

CMD ["npm","run","start"]

