version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.1.1
executors:
  docker-executor:
    docker:
      - image: cimg/node:21.1.0



jobs:
 
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws_access_key_id : $AWS_ACCESS_KEY
          aws_secret_access_key: $AWS_ACCESS_SECRET
         

  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Switch to Dockerfile Directory
          command: cd ..
      - run:
          name: Build and Test
          command: |
            docker build -t hardik89990/docker-react -f Dockerfile.dev .
            docker run -e CI=true hardik89990/docker-react npm run test

