version: 2.1
orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
executors:
  docker-executor:
    docker:
      - image: cimg/node:21.1.0



jobs:
 
  aws-cli-cred-setup:
    environment:
      aws_access_key_id : $AWS_ACCESS_KEY
      aws_secret_access_key: $AWS_ACCESS_SECRET
    executor: aws-cli/default
    steps:
      - checkout
      - run: |
          aws_access_key_id : $AWS_ACCESS_KEY
          aws_secret_access_key: $AWS_ACCESS_SECRET

  - aws-elastic-beanstalk/deploy:
            application-name: Container-app 
            environment-name: Container-app-env 
            platform-version: Docker running on 64bit Amazon Linux 2023/4.1.0
         

  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Switch to Dockerfile Directory
          command: cd ..
      - run:
          name: Build and Test
          command: |
            docker build -t hardik89990/docker-react -f Dockerfile.dev .
            docker run -e CI=true hardik89990/docker-react npm run test


