version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/node:21.1.0

jobs:
  build:
    docker:
      - image: cimg/node:21.1.0
    steps:
      - checkout
      - run:
          name: Switch to Dockerfile Directory
          command: cd ..
      - run:
          name: Build and Test
          command: |
            docker build -t hardik89990/docker-react -f Dockerfile.dev .
            docker run -e CI=true hardik89990/docker-react npm run test

  deploy:
    docker:
      - image: circleci/aws-elasticbeanstalk:2.4.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Deploy to Elastic Beanstalk
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY
            aws configure set aws_secret_access_key $AWS_SECRET_KEY
            aws elasticbeanstalk create-application-version --application-name "Conatainer-app" --version-label $CIRCLE_SHA1 --source-bundle S3Bucket="elasticbeanstalk-ap-south-1-941863037293",S3Key="Conatainer-app/$CIRCLE_SHA1.zip"
            aws elasticbeanstalk update-environment --environment-name "Conatainer-app-env" --version-label $CIRCLE_SHA1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
