version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Switch to Dockerfile Directory
          command: cd /path/to/your/dockerfile/directory
      - run:
          name: Build and Test
          command: |
            docker build -t hardik89990/docker-react -f Dockerfile.dev .
            docker run hardik89990/docker-react npm run test -- --coverage

workflows:
  version: 2
  build:
    jobs:
      - build

